---
# tasks file for linux
- name: Set facts
  set_fact:
    transparent_proxy_instance: "{{ program }}-{{ server }}"
  when: transparent_proxy_instance is not defined

- name: Set facts
  set_fact:
    config_file: "{{ transparent_proxy_instance }}-config.json"
    dnsmasq_conf_dir: "{{ remote_prefix }}/{{ dnsmasq_china_list_name }}"

- name: Randomly select doh servers
  set_fact:
    doh_servers:
      "{{ (doh_servers | shuffle)[:number_of_doh_servers_to_use] }}"
    doh_servers_using_proxy:
      "{{ (doh_servers_using_proxy | shuffle)[:number_of_doh_servers_using_proxy_to_use] }}"

- name: Randomly select dns servers
  set_fact:
    global_dns_servers:
      "{{ (global_dns_servers | shuffle)[:number_of_global_dns_servers_to_use] }}"
    china_dns_servers:
      "{{ (china_dns_servers | shuffle)[:number_of_china_dns_servers_to_use] }}"

- name: Randomly select v2ray dokodemo door dns servers
  set_fact:
    v2ray_dns_dokodemo_door_ports:
      "{{ (range(10053, 10053 + v2ray_upstream_dns_servers|length) | list | shuffle)[:number_of_v2ray_upstream_dns_servers_to_use] }}"

- name: Ensure directories exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_real_user_id }}"
    mode: 0755
  loop:
    - "{{ remote_prefix }}"
    - "{{ remote_prefix }}/conf.d"
    - "{{ systemd_unit_dest }}"

- name: Create systemd unit
  template:
    src: "{{ unit }}@.service.j2"
    dest: "{{ systemd_unit_dest }}/{{ unit }}@.service"
    owner: root
    group: root
    mode: 0644
  become: on
  become_user: root
  loop:
    - transparent-proxy
  loop_control:
    loop_var: unit
  notify: "Restart transparent-proxy@"

- name: Create systemd unit
  template:
    src: "{{ unit }}@.service.j2"
    dest: "{{ systemd_unit_dest }}/{{ unit }}@.service"
    owner: root
    group: root
    mode: 0644
  become: on
  become_user: root
  loop:
    - my-proxy
  loop_control:
    loop_var: unit

- name: Create systemd unit
  template:
    src: "{{ unit }}.service.j2"
    dest: "{{ systemd_unit_dest }}/{{ unit }}.service"
    owner: root
    group: root
  become: on
  become_user: root
  loop:
    - clean-dns
  loop_control:
    loop_var: unit
  notify: "Restart clean-dns"

- name: Create config files
  template:
    src: "{{ item }}.j2"
    dest: "{{ remote_prefix }}/{{ item }}"
  loop:
    - "dnsmasq.conf"
  notify: "Restart clean-dns"

- name: Chattr of resolv.conf
  shell: |
    chattr -i '{{ remote_prefix }}/{{ item }}'
  loop:
    - "resolv.conf"
  ignore_errors: True

- name: Create config files
  template:
    src: "{{ item }}.j2"
    dest: "{{ remote_prefix }}/{{ item }}"
    mode: 0444
  loop:
    - "resolv.conf"
  notify: "Restart clean-dns"

- name: Chattr of resolv.conf
  shell: |
    chattr +i '{{ remote_prefix }}/{{ item }}'
  loop:
    - "resolv.conf"
  ignore_errors: True

- name: Create clean-dns script
  template:
    src: "{{ item }}.j2"
    dest: "{{ remote_prefix }}/{{ item }}"
    mode: 0755
  loop:
    - "clean-dns"
  notify: "Restart clean-dns"

- name: Create transparent-proxy script
  template:
    src: "{{ item }}.j2"
    dest: "{{ remote_prefix }}/{{ item }}"
    mode: 0755
  loop:
    - "transparent-proxy"
  notify: "Restart transparent-proxy@"

- name: Copy v2ray to remote
  copy:
    src: "./artifacts/{{ item }}"
    dest: "{{ remote_prefix }}"
    force: "{{ update }}"
    mode: preserve
  loop:
    - "{{ v2ray_name }}"
  notify: "Restart transparent-proxy@"

- name: Copy ss-nat to remote
  copy:
    src: "./artifacts/{{ item }}"
    dest: "{{ remote_prefix }}/{{ item }}"
    mode: 0755
    force: "{{ update }}"
  loop:
    - "{{ ss_nat_name }}"
  notify: "Restart transparent-proxy@"

- name: Copy files to remote
  copy:
    src: "./artifacts/{{ item }}"
    dest: "{{ remote_prefix }}/{{ item }}"
    force: yes
  loop:
    - "{{ doh_servers_name }}"
    - "{{ china_ip_list_name }}"
    - "{{ directly_connecting_domains_name }}"
    - "{{ dnsmasq_china_list_name }}/"
  notify: "Restart transparent-proxy@"

- name: Copy dnsmasq_china_list to remote
  copy:
    src: "./artifacts/{{ item }}"
    dest: "{{ remote_prefix }}/{{ item }}"
    force: yes
  loop:
    - "{{ dnsmasq_china_list_name }}/"
  notify: "Restart clean-dns"

- name: Copy configurations to remote
  copy:
    src: "./artifacts/{{ item }}"
    dest: "{{ remote_prefix }}/conf.d/{{ item }}"
    force: yes
  loop:
    - "{{ config_file }}"
  notify: "Restart transparent-proxy@"

- name: Create env for remote
  template:
    src: "{{ item }}.j2"
    dest: "{{ remote_prefix }}/conf.d/{{transparent_proxy_instance}}-{{ item }}"
    force: yes
  loop:
    - env
  notify: "Restart transparent-proxy@"

- name: Create env for remote
  template:
    src: "{{ item }}.j2"
    dest: "{{ remote_prefix }}/conf.d/default-{{ item }}"
    force: yes
  loop:
    - env
  notify: "Restart clean-dns"
