---
- name: restart v2ray-redir
  service:
    name: v2ray-redir
    enabled: yes
    state: restarted
  when: (enable_service == 'yes') and (program == 'v2ray')

- name: restart shadowsocks-libev-redir
  service:
    name: shadowsocks-libev-redir
    enabled: yes
    state: restarted
  when: (enable_service == 'yes') and (program == 'shadowsocks-libev')

- name: stop v2ray-redir
  service:
    name: v2ray-redir
    state: stopped

- name: stop shadowsocks-libev-redir
  service:
    name: shadowsocks-libev-redir
    state: stopped

- name: restart dnsmasq
  service:
    name: dnsmasq
    enabled: yes
    state: restarted

- name: reload https_dns_proxy
  service:
    name: https_dns_proxy
    enabled: yes
    state: reloaded
